In [2]:
# import required libraries
import pandas as pd
import numpy as np

In [4]:
# Reading the dataset
df = pd.read_csv('50_Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [6]:
df.shape

(50, 5)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [10]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [12]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [14]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()

In [15]:
df['State'] = le.fit_transform(df.State)

In [18]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [20]:
X =df.iloc[:,:-1].values

In [22]:
y= df.iloc[:,4:5].values

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [26]:
x_train.shape, x_test.shape

((35, 4), (15, 4))

In [30]:
pip install tensorflow


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.0/227.0 MB 3.0 MB/s eta 0:00:0000:0100:02
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 3.2 MB/s eta 0:00:0000:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 3.6 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 3.8 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 4.0 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.4/26.4 MB 3.8 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 389.8/389.8 kB 4.5 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 3.9 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 3.8 MB/s et

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [34]:
# creating ANN skeleton

regressor = Sequential()
regressor.add(Dense(4,activation='relu'))# input layer
regressor.add(Dense(8,activation='relu')) # first Hidden layer
regressor.add(Dense(16,activation='relu')) # 2nd Hidden layer
regressor.add(Dense(1,activation='linear')) # Output Layer


In [36]:
# Compiling ANN model

regressor.compile(optimizer='adam',loss ='mse',metrics=['mse'] )


In [38]:
# training the model
regressor.fit(x_train,y_train,batch_size=10,epochs =300)


Epoch 1/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 15280754688.0000 - mse: 15280754688.0000  
Epoch 2/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15691102208.0000 - mse: 15691102208.0000 
Epoch 3/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 15128573952.0000 - mse: 15128573952.0000 
Epoch 4/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14402349056.0000 - mse: 14402349056.0000 
Epoch 5/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13577218048.0000 - mse: 13577219072.0000 
Epoch 6/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13372535808.0000 - mse: 13372535808.0000 
Epoch 7/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13555896320.0000 - mse: 13555896320.0000 
Epoch 8/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14586253312.0000 - mse: 14586252288.0000 
Epoch 9/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 15494150144.0000 - mse: 15494150144.0000 
Epoch 10/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14153294848.0000 - mse: 14153294848.0000 
Epoch 11

In [40]:
# testing the model

y_pred = regressor.predict(x_test)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


In [42]:
y_pred

array([[115136.28 ],
       [122011.055],
       [120800.81 ],
       [ 59534.24 ],
       [176235.7  ],
       [122866.01 ],
       [ 51851.496],
       [101414.68 ],
       [117213.89 ],
       [161150.25 ],
       [ 89185.66 ],
       [ 76999.89 ],
       [108623.71 ],
       [ 95391.35 ],
       [126530.97 ]], dtype=float32)

In [44]:
from sklearn.metrics import r2_score

In [46]:
# evaluating the model with r2 score

r2_score(y_test,y_pred)

0.7546794123196735

In [48]:
y_pred.flatten()

array([115136.28 , 122011.055, 120800.81 ,  59534.24 , 176235.7  ,
       122866.01 ,  51851.496, 101414.68 , 117213.89 , 161150.25 ,
        89185.66 ,  76999.89 , 108623.71 ,  95391.35 , 126530.97 ],
      dtype=float32)

In [50]:
# Comparing the actual and predicted y values

pd.DataFrame({'Actual y_value':y_test.flatten(),'Predicted y_value':y_pred.flatten()}).head(10)

Actual y_value  Predicted y_value
0       103282.38      115136.281250
1       144259.40      122011.054688
2       146121.95      120800.812500
3        77798.83       59534.238281
4       191050.39      176235.703125
5       105008.31      122866.007812
6        81229.06       51851.496094
7        97483.56      101414.679688
8       110352.25      117213.890625
9       166187.94      161150.250000

In [52]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [54]:
inputx=np.array([[142107.34,91391.77,366168.42 ,1]])

In [58]:
# testing with random values

regressor.predict(inputx)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step


array([[161150.25]], dtype=float32)