In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [4]:
dataset=pd.read_csv('Churn_Modelling.csv')

In [6]:
type(dataset)

pandas.core.frame.DataFrame

In [8]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [10]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          225     Spain  Female   41   
2          3    15619304      Onio          629    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [12]:
dataset['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [14]:
x=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13:14].values

In [16]:

x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [225, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [629, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [18]:
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]])

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [22]:
x.shape

(10000, 10)

In [24]:
ct=ColumnTransformer([('oh',OneHotEncoder(),[1,2])],remainder='passthrough')
x=ct.fit_transform(x)

In [26]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [28]:
x.shape

(10000, 13)

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [32]:
from sklearn.preprocessing import StandardScaler
sa=StandardScaler()


In [36]:
import joblib
joblib.dump(sa,"sc")

['sc']

In [38]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [40]:
x_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [42]:
from tensorflow.keras.models import Sequential
from keras.layers import Dense

In [43]:
model=Sequential()

In [46]:
x.shape

(10000, 13)

In [48]:
model.add(Dense(units=13,activation='relu',kernel_initializer='random_uniform'))# input layer

In [50]:
model.add(Dense(units=26,activation='relu',kernel_initializer='random_uniform'))

In [52]:
model.add(Dense(units=26,activation='relu',kernel_initializer='random_uniform'))

In [54]:
model.add(Dense(units=1,activation='sigmoid',kernel_initializer='random_uniform'))

In [56]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [58]:
x_train.shape

(8000, 13)

In [60]:
model.fit(x_train,y_train,batch_size=32,epochs=20)

Epoch 1/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 498us/step - accuracy: 0.7853 - loss: 0.5811
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.7959 - loss: 0.4212
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8325 - loss: 0.3933
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.8502 - loss: 0.3788
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.8597 - loss: 0.3527
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8496 - loss: 0.3650
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 513us/step - accuracy: 0.8626 - loss: 0.3407
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - accuracy: 0.8645 - loss: 0.3402
Epoch 9/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.8576 - loss: 0.3456
Epoch 10/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.8568 - loss: 0.3472
Epoch 11/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.8676 - loss: 0.3354
Epoch 12/20
250/250 ━━━━━━━━━━━━

In [62]:
ypred=model.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step


In [64]:
ypred

array([[0.2213143 ],
       [0.26946795],
       [0.13196972],
       ...,
       [0.14814398],
       [0.17944822],
       [0.16074272]], dtype=float32)

In [66]:
ypred=ypred>0.5
ypred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [68]:
y_test

array([[0],
       [1],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [70]:
dataset.head(1)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

In [72]:
x.shape

(10000, 13)

In [74]:
x[0] = np.array(x[0].astype(np.float32))

In [76]:
x[0].dtype

dtype('O')

In [78]:
x[0]

array([1.0, 0.0, 0.0, 1.0, 0.0, 619.0, 42.0, 2.0, 0.0, 1.0, 1.0, 1.0,
       101348.8828125], dtype=object)

In [90]:
y_s=model.predict(np.array([[1.0, 0.0, 0.0, 1.0, 0.0, 619, 42, 2, 0.0, 1, 1, 1, 101348.88]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


In [92]:
y_s

array([[0.]], dtype=float32)

In [94]:
y_s

array([[0.]], dtype=float32)

In [96]:
p=np.array(sc.transform(ct.transform([[875,'France','Female',42,5,1234,0,1,1,1234567]])))

In [98]:
p

array([[ 1.04501206, -0.61433742, -0.57427105,  1.11339196, -1.11339196,
         2.35839422,  0.26349271, -0.04867536, -1.24761801, -2.54811601,
         0.66011376,  0.97628121, 19.77099386]])

In [100]:
yp=model.predict(p)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


In [102]:
yp

array([[0.46363562]], dtype=float32)

In [104]:
yp=yp>0.5
yp

array([[False]])