In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("Fish.csv")

In [6]:
data

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [8]:
data.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [10]:
data['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [12]:
data.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [16]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
data['Species'] = label_encoder.fit_transform(data['Species'])

In [18]:
data.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0        0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0   430.0     26.5     29.0     34.0  12.4440  5.1340

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    int64  
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), int64(1)
memory usage: 8.8 KB


In [22]:
x=data.iloc[:,1:7].values
y=data.iloc[:,0:1].values


In [24]:
x

array([[2.42000e+02, 2.32000e+01, 2.54000e+01, 3.00000e+01, 1.15200e+01,
        4.02000e+00],
       [2.90000e+02, 2.40000e+01, 2.63000e+01, 3.12000e+01, 1.24800e+01,
        4.30560e+00],
       [3.40000e+02, 2.39000e+01, 2.65000e+01, 3.11000e+01, 1.23778e+01,
        4.69610e+00],
       [3.63000e+02, 2.63000e+01, 2.90000e+01, 3.35000e+01, 1.27300e+01,
        4.45550e+00],
       [4.30000e+02, 2.65000e+01, 2.90000e+01, 3.40000e+01, 1.24440e+01,
        5.13400e+00],
       [4.50000e+02, 2.68000e+01, 2.97000e+01, 3.47000e+01, 1.36024e+01,
        4.92740e+00],
       [5.00000e+02, 2.68000e+01, 2.97000e+01, 3.45000e+01, 1.41795e+01,
        5.27850e+00],
       [3.90000e+02, 2.76000e+01, 3.00000e+01, 3.50000e+01, 1.26700e+01,
        4.69000e+00],
       [4.50000e+02, 2.76000e+01, 3.00000e+01, 3.51000e+01, 1.40049e+01,
        4.84380e+00],
       [5.00000e+02, 2.85000e+01, 3.07000e+01, 3.62000e+01, 1.42266e+01,
        4.95940e+00],
       [4.75000e+02, 2.84000e+01, 3.10000e+01, 3.6

In [26]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
    

In [28]:
y.dtype

dtype('int64')

In [30]:
x.shape

(159, 6)

In [32]:
y.shape

(159, 1)

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [36]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


# Model Building

In [39]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [41]:
model = Sequential()

In [43]:
x.shape

(159, 6)

In [45]:
model.add(Dense(units = 6,kernel_initializer = 'random_uniform',activation = 'relu')) #input layer

In [47]:
model.add(Dense(units =12,kernel_initializer = 'random_uniform',activation = 'relu')) # 1st hidden layer

In [49]:
model.add(Dense(units = 7 ,kernel_initializer = 'random_uniform',activation = 'softmax')) #Output Layer

In [51]:
model.compile (optimizer = 'adam',loss = 'sparse_categorical_crossentropy',metrics = ['accuracy'])

In [53]:
model.fit(x_train,y_train , batch_size = 32,epochs = 300)

Epoch 1/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2509 - loss: 1.9455  
Epoch 2/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3782 - loss: 1.9431 
Epoch 3/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3449 - loss: 1.9407 
Epoch 4/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3262 - loss: 1.9389 
Epoch 5/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3814 - loss: 1.9358 
Epoch 6/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3720 - loss: 1.9336 
Epoch 7/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3491 - loss: 1.9317 
Epoch 8/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3876 - loss: 1.9285 
Epoch 9/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3407 - loss: 1.9253 
Epoch 10/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.3814 - loss: 1.9220
Epoch 11/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3907 - loss: 1.9179 
Epoch 12/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3324 - l

In [55]:
y_pred = model.predict(x_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step


In [57]:
y_pred #Predicted Value

array([[8.79377246e-01, 7.86430910e-02, 1.49791529e-02, 2.14339845e-04,
        6.95675798e-03, 7.51114203e-06, 1.98219288e-02],
       [6.62277535e-06, 6.65260255e-02, 5.31957388e-01, 1.96821972e-07,
        2.47130617e-01, 1.52681038e-01, 1.69818965e-03],
       [1.96013716e-05, 6.11493997e-02, 5.56143701e-01, 1.92116818e-06,
        2.60626048e-01, 1.18830480e-01, 3.22887371e-03],
       [7.64268771e-05, 1.01028994e-01, 5.39584279e-01, 3.40805013e-06,
        2.70997524e-01, 8.27979743e-02, 5.51141985e-03],
       [2.25836396e-01, 3.37431170e-02, 5.69698691e-01, 3.62658277e-02,
        4.28847931e-02, 9.79904326e-06, 9.15614218e-02],
       [1.62887648e-01, 3.86134721e-03, 7.56319463e-01, 3.31336521e-02,
        7.39563769e-03, 2.32847697e-08, 3.64022069e-02],
       [4.58823621e-01, 2.08727494e-02, 4.31868702e-01, 1.25476196e-02,
        1.61416363e-02, 4.16484653e-07, 5.97451515e-02],
       [4.02141875e-03, 1.24337804e-03, 7.84072101e-01, 1.78485632e-01,
        1.20854387e-02, 1

In [59]:
y_test.flatten() #Actual Value

array([0, 4, 2, 4, 2, 2, 6, 3, 0, 2, 3, 3, 6, 2, 1, 4, 4, 3, 2, 0, 1, 4,
       2, 3, 1, 0, 0, 6, 2, 5, 0, 2])

In [61]:
y_test[0]

array([0])

In [63]:
y_pred[0]

array([8.7937725e-01, 7.8643091e-02, 1.4979153e-02, 2.1433985e-04,
       6.9567580e-03, 7.5111420e-06, 1.9821929e-02], dtype=float32)

In [65]:
output=np.argmax(y_pred[0])

In [67]:
output

0

In [69]:
data.head(1)

Species  Weight  Length1  Length2  Length3  Height  Width
0        0   242.0     23.2     25.4     30.0   11.52   4.02

In [71]:
y_p = model.predict((sc.transform([[242,23.2,23,30,11,4]])))
                    

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


In [73]:
y_p

array([[1.8021309e-01, 4.9752891e-01, 1.5779534e-01, 1.3825519e-04,
        1.0297483e-01, 1.2131138e-03, 6.0136430e-02]], dtype=float32)

In [75]:
index = ['Bream', 'Parkki','Perch','Pike','Roach', 'Smelt','Whitefish']

In [77]:
p=np.argmax(y_p)

In [79]:
p

1

In [81]:
index[p]

'Parkki'